apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: pingdirectory
        resources:
          limits:
            memory: 16Gi
          requests:
            memory: 16Gi
            cpu: 2
      - name: stunnel
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-gp2
      resources:
        requests:
          storage: 50Gi